
-- QUESTION 06
select * from OEHR_DEPARTMENTS;

-- QUESTION 07
SELECT * FROM OEHR_EMPLOYEES;
SELECT 	PHONE_NUMBER AS "EMPLOYEE_NUMBER", LAST_NAME, JOB_ID AS "JOB_CODE", HIRE_DATE FROM OEHR_EMPLOYEES;

-- QUESTION 09
SELECT DISTINCT(JOB_ID) AS "UNIQUE_JOB_CODES" FROM OEHR_EMPLOYEES;

-- QUESTION 11
SELECT LAST_NAME || ', ' || JOB_ID AS "Employee and Title" FROM OEHR_EMPLOYEES;

-- QUESTION 12
SELECT EMPLOYEE_ID|| ',' ||FIRST_NAME|| ',' ||LAST_NAME|| ',' ||LAST_NAME|| ',' ||PHONE_NUMBER|| ',' ||HIRE_DATE|| ',' ||JOB_ID|| ',' ||SALARY|| ',' ||COMMISSION_PCT|| ',' ||MANAGER_ID|| ',' ||DEPARTMENT_ID AS "THE_OUTPUT" FROM OEHR_EMPLOYEES;
